[package]
name = "calling_github_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.139"
serde = {version = "1.0.139", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
