[package]
name = "spotify_api_search"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.139"
serde = { version = "1.0.139", features = ["derive"]}
tokio = { version = "1.43.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
futures = "0.3"